stages:
  - test

.setup:
  image: python:3.12
  before_script:
    - apt-get update -qy
    - export POETRY_VERSION=2.1.1
    - export POETRY_VIRTUALENVS_CREATE=false
    - export POETRY_CACHE_DIR='/var/cache/pypoetry'
    - export POETRY_HOME='/usr/local'
    - curl -sSL https://install.python-poetry.org | python3
    - poetry install --no-ansi --no-interaction

mypy:
  extends: .setup
  stage: test
  script:
    - mypy --strict app

pytest:
  extends: .setup
  stage: test
  script:
    - pytest tests

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
