"""Add student_message table

Revision ID: 83704023398b
Revises: b4a73ef55369
Create Date: 2025-04-29 00:09:04.101926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83704023398b'
down_revision: Union[str, None] = 'b4a73ef55369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('thread_message_id', sa.Integer(), nullable=True),
    sa.Column('thread_chat_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('received_reaction', sa.Boolean(), nullable=False),
    sa.Column('received_reaction_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reaction_message_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_message')
    # ### end Alembic commands ###
