"""Add created_at

Revision ID: a4e6609c3a50
Revises: ee49be1a242a
Create Date: 2025-03-02 20:57:00.702381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e6609c3a50'
down_revision: Union[str, None] = 'ee49be1a242a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_ticket_sub', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread_ticket_sub', 'created_at')
    # ### end Alembic commands ###
