"""Add course field

Revision ID: b0f0103ff177
Revises: 9706635a76be
Create Date: 2025-05-06 14:48:44.352591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f0103ff177'
down_revision: Union[str, None] = '9706635a76be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_message', sa.Column('course', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_message', 'course')
    # ### end Alembic commands ###
